import { useEffect, useState } from "react";
import { isletmeleriGetir, kayitlariGetir } from "../lib/superApi";
import { Hata, tarih, Yukleme } from "../components/Ui";

export default function Kayitlar() {
  const [filtre, setFiltre] = useState({ islem: "", isletmeId: "", baslangic: "", bitis: "", limit: 200 }), [veri, setVeri] = useState(null), [isletmeler, setIsletmeler] = useState([]), [hata, setHata] = useState("");
  useEffect(() => { isletmeleriGetir().then((v) => setIsletmeler(v.isletmeler)).catch(() => {}); }, []);
  useEffect(() => { const timer = setTimeout(() => { setVeri(null); setHata(""); kayitlariGetir(filtre).then((v) => setVeri(v.kayitlar)).catch((e) => setHata(e.message)); }, 200); return () => clearTimeout(timer); }, [filtre]);
  return <div className="sayfa"><div className="sayfa-araclari"><div><h2>Super admin denetim izi</h2><p>Kim, ne zaman, hangi işletme üzerinde ne yaptı?</p></div></div><section className="filtreler kayit-filtre"><input placeholder="İşlem tipinde ara…" value={filtre.islem} onChange={(e) => setFiltre({ ...filtre, islem: e.target.value })} /><select value={filtre.isletmeId} onChange={(e) => setFiltre({ ...filtre, isletmeId: e.target.value })}><option value="">Tüm işletmeler</option>{isletmeler.map((i) => <option key={i.id} value={i.id}>{i.ad}</option>)}</select><input type="date" value={filtre.baslangic} onChange={(e) => setFiltre({ ...filtre, baslangic: e.target.value })} /><input type="date" value={filtre.bitis} onChange={(e) => setFiltre({ ...filtre, bitis: e.target.value })} /><span>{veri?.length || 0} kayıt</span></section><Hata mesaj={hata} />{!veri && !hata ? <Yukleme /> : veri && <section className="tablo-panel"><table><thead><tr><th>Zaman</th><th>Super admin</th><th>İşlem</th><th>İşletme</th><th>IP</th><th>Ayrıntı</th></tr></thead><tbody>{veri.map((k) => <tr key={k.id}><td><time>{tarih(k.olusturma)}</time></td><td><b>{k.superAdmin.ad}</b><small>{k.superAdmin.email}</small></td><td><code>{k.islem}</code></td><td>{k.isletmeAd}<small>{k.isletmeSlug ? `/${k.isletmeSlug}` : ""}</small></td><td>{k.ip || "—"}</td><td><details><summary>Göster</summary><pre>{JSON.stringify(k.detay, null, 2)}</pre></details></td></tr>)}</tbody></table></section>}</div>;
}
