// Yalnızca uygulamanın kendi arayüz metinleri. İşletmenin girdiği içerikler çevrilmez.
export const ARAYUZ_CEVIRILERI = {
  "Özel Fırsatlar ve Kampanyalar": "Special Offers and Campaigns",
  "Sana özel hazırladığımız lezzetli fırsatları kaçırma.": "Don't miss the delicious offers prepared for you.",
  "Üyelere Özel": "Members Only", "Üyelere özel": "Members only", "🔒 Üyelere Özel": "🔒 Members Only",
  "Üyelere Özel Kampanya": "Members-Only Campaign",
  "Bu kampanyadan faydalanmak için üye olmalısın.": "You need to become a member to use this campaign.",
  "Davet kodun": "Your referral code", "Kopyala": "Copy", "Kopyalandı": "Copied", "puan kazanç": "points earned",
  "Sipariş Ver": "Order Now", "Kapat": "Close", "Üye Ol": "Sign Up",
  "Sepetim": "My Cart", "Sepetin boş": "Your cart is empty",
  "Sepetin boş, önce ürün ekle.": "Your cart is empty. Add a product first.", "Menüye Dön": "Back to Menu",
  "HEDİYE 🎁": "GIFT 🎁", "Toplam": "Total", "Nasıl sipariş vermek istersin?": "How would you like to order?",
  "Al Götür": "Takeaway", "Masaya Servis": "Table Service", "Ödemeye Geç": "Continue to Payment",
  "Geri": "Back", "Kaldır": "Remove", "Azalt": "Decrease", "Artır": "Increase",
  "Kullanıldı ✓": "Used ✓", "Hediyelerim": "My Rewards", "Kullanılabilir Hediyeler": "Available Rewards",
  "Henüz hediye kazanmadın": "You haven't earned a reward yet", "Kullanılmış Hediyeler": "Used Rewards",
  "Henüz kullanılmış hediye yok": "No rewards have been used yet", "Hediyeyi Kullan": "Use Reward", "İşleniyor…": "Processing…",
  "TAMAMLANDI": "COMPLETED", "SIRADAKİ ÖDÜL": "NEXT REWARD", "Damga": "Stamp", "Hediye": "Reward",
  "Kayıt Ol": "Sign Up", "Ad": "First Name", "Soyad": "Last Name", "Ad Soyad": "Full Name",
  "Cinsiyet": "Gender", "Kadın": "Female", "Erkek": "Male", "Belirtmek istemiyorum": "Prefer not to say",
  "E-posta": "Email", "Telefon": "Phone", "Şifre": "Password", "Davet kodu": "Referral code",
  "(isteğe bağlı)": "(optional)", "Bir arkadaşın davet ettiyse kodunu buraya yaz.": "Enter the code here if a friend invited you.",
  "Giriş Yap": "Sign In", "Zaten hesabın var mı?": "Already have an account?", "Hesabın yok mu?": "Don't have an account?",
  "Adın": "Your first name", "Soyadın": "Your last name", "En az 8 karakter": "At least 8 characters", "8 haneli kod": "8-character code",
  "Siparişin Alındı!": "Your Order Has Been Received!", "Masa": "Table", "Durum": "Status", "Hazırlanıyor": "Preparing",
  "✓ Ödeme tamamlandı": "✓ Payment completed", "Siparişlerim": "My Orders",
  "Henüz siparişin yok": "You don't have any orders yet", "Sipariş verdiğinde burada görünecek.": "Your orders will appear here.",
  "Siparişler yükleniyor…": "Loading orders…", "Aktif Siparişler": "Active Orders", "Geçmiş Siparişler": "Past Orders",
  "Sipariş no": "Order number", "Masada ödenecek": "Pay at the table", "Ödeme": "Payment",
  "👤 Misafir olarak devam ediyorsun": "👤 You are continuing as a guest", "Sipariş özeti": "Order summary",
  "Ödeme türü": "Payment method", "Online ödeme": "Online payment", "Şimdi güvenle öde": "Pay securely now",
  "Cüzdan bakiyesi": "Wallet balance", "Nakit ödeme": "Cash payment", "İletişim bilgileri": "Contact information",
  "Kart bilgilerin İyzico’nun güvenli ödeme sayfasında girilir. Normal siparişte T.C. kimlik ve adres bilgisi istenmez.": "Your card details are entered on Iyzico's secure payment page. ID and address details are not requested for a standard order.",
  "Nasıl ödemek istersin?": "How would you like to pay?",
  "Cüzdan bakiyen bu sipariş için yetersiz. Kasadan nakit yükleme yapabilirsin.": "Your wallet balance is insufficient for this order. You can top up with cash at the register.",
  "Kaç kişi paylaşıyor?": "How many people are sharing?", "Ödeyeceğin ürünleri seç": "Select the items you will pay for",
  "kazanacaksın": "you will earn", "Ödenecek Tutar": "Amount Due",
  "Ödeme sonucun doğrulanıyor…": "Verifying your payment…", "Ödemeye Dön": "Back to Payment",
  "Görüntülenecek ödeme yok.": "There is no payment to display.", "Ana Sayfa": "Home", "Ödeme Başarılı!": "Payment Successful!",
  "Siparişin Hazırlanıyor": "Your Order Is Being Prepared", "Mutfağa iletildi, hazırlanıyor.": "Sent to the kitchen and being prepared.",
  "Ödenen Tutar": "Amount Paid", "Kazandığın Puan": "Points Earned",
  "Profili Düzenle": "Edit Profile", "Hesap Bilgileri": "Account Information", "🔒 Değiştirilemez": "🔒 Cannot be changed",
  "Profil görseli": "Profile image", "JPG, PNG veya WebP · en fazla 1,5 MB": "JPG, PNG or WebP · maximum 1.5 MB",
  "Görsel seç": "Choose Image", "Görseli kaldır": "Remove Image", "✓ Bilgilerin güncellendi": "✓ Your information has been updated",
  "Kaydet": "Save", "Kaydediliyor…": "Saving…", "Düzenle": "Edit", "İşletme": "Business", "Çıkış Yap": "Sign Out",
  "Masa QR Kodları": "Table QR Codes", "Masalar için QR üret ve yazdır": "Generate and print QR codes for tables",
  "İki Adımlı Doğrulama": "Two-Factor Authentication", "Nasıl yardımcı olabiliriz?": "How can we help?",
  "Destek saatleri: Her gün 10:00 – 23:00": "Support hours: Every day, 10:00–23:00", "Mevcut şifre": "Current password",
  "Kurulumu Başlat": "Start Setup", "6 haneli kod": "6-digit code", "Etkinleştir": "Enable",
  "Kodları Kopyala": "Copy Codes", "Kaydettim, Bitir": "I've Saved Them, Finish",
  "Doğrulama veya kurtarma kodu": "Verification or recovery code", "İki Adımlı Doğrulamayı Kapat": "Disable Two-Factor Authentication", "Vazgeç": "Cancel",
  "Kaç masa için QR üretilsin?": "How many tables should QR codes be generated for?", "QR'ları Oluştur": "Generate QR Codes",
  "🖨️ Yazdır": "🖨️ Print", "Okut · Sipariş Ver · Öde": "Scan · Order · Pay", "QR Okut": "Scan QR",
  "Kamera açılıyor…": "Opening camera…", "QR kodu çerçeve içine hizala": "Align the QR code inside the frame", "Devam Et": "Continue", "Masa numarası": "Table number",
  "Toplam Puanım": "My Total Points", "Puan": "Points", "Başlangıç": "Start", "Hediyeye sadece": "Only",
  "kaldı!": "left until your reward!", "Ödül Marketi": "Rewards Store", "Puan Geçmişi": "Points History", "Tümünü Gör": "View All",
  "Şifreni mi unuttun?": "Forgot your password?", "Bağlantı gönderildi": "Link Sent", "Şifreni sıfırla": "Reset Your Password",
  "E-posta adresini gir, sıfırlama bağlantısı gönderelim.": "Enter your email address and we'll send you a reset link.",
  "Gönder": "Send", "Gönderiliyor…": "Sending…", "Yeni şifreni belirle": "Set your new password",
  "Bağlantı kontrol ediliyor…": "Checking link…", "Bağlantı geçersiz": "Invalid Link", "Şifren güncellendi": "Your Password Has Been Updated",
  "Giriş ekranına yönlendiriliyorsun…": "Redirecting you to the sign-in screen…", "Yeni şifre belirle": "Set a New Password",
  "Yeni şifre": "New password", "Yeni şifre (tekrar)": "New password (again)", "Şifreler eşleşmiyor.": "Passwords do not match.",
  "Şifremi Güncelle": "Update My Password", "Güncelleniyor...": "Updating...",
  "GERİ BİLDİRİM MERKEZİ": "FEEDBACK CENTER", "Şikayet ve öneri": "Complaints and Suggestions",
  "Yaşadığınız durumu doğrudan işletme yöneticisine iletin.": "Send your experience directly to the business manager.",
  "Yeni başvuru": "New Request", "Açıklayıcı bilgi çözüm süresini hızlandırır.": "Clear details help speed up the resolution.",
  "Kategori": "Category", "Konu": "Subject", "Açıklama": "Description", "Görsel ekle": "Add Image",
  "İsteğe bağlı · PNG, JPG veya WebP · en fazla 5 MB": "Optional · PNG, JPG or WebP · maximum 5 MB",
  "TAKİP": "TRACKING", "Başvurularım": "My Requests", "Başvurular yükleniyor…": "Loading requests…",
  "Henüz bir başvurunuz bulunmuyor.": "You don't have any requests yet.", "Profile dön": "Back to Profile",
  "Kısaca ne oldu?": "Briefly, what happened?", "Tarih, masa veya sipariş bilgisiyle birlikte yaşadığınız durumu anlatın.": "Describe what happened, including the date, table or order details.",
  "Gönderiliyor...": "Submitting...", "Başvuruyu Gönder": "Submit Request", "Masanız": "Your Table", "Siparişin": "Your Order",
  "Menü İçeriği": "Menu Contents", "Yan lezzet": "Side", "İçecek": "Drink", "Besin Değerleri": "Nutrition Facts",
  "Alerjen Bilgisi": "Allergen Information", "İçindekiler": "Ingredients", "İstemediğin malzemeye dokun": "Tap any ingredient you don't want",
  "YANINDA İYİ GİDER": "GOES WELL WITH", "Siparişini tamamla": "Complete your order", "Ekle": "Add", "Sepete Ekle": "Add to Cart",
  "Gramajı azalt": "Decrease portion", "Gramajı artır": "Increase portion",
  "🎁 Her siparişte puan kazan": "🎁 Earn points with every order", "🍔 Puanlarını ürünlerle takas et": "🍔 Exchange your points for products",
  "⭐ 5 al 1 bedava gibi ödüller": "⭐ Rewards such as buy 5, get 1 free", "📋 Sipariş geçmişini gör": "📋 View your order history",
  "Cüzdanım": "My Wallet", "Uygulama bakiyesi": "App Balance", "SADECE BU İŞLETMEDE": "ONLY AT THIS BUSINESS",
  "Bakiyeni sipariş ödemelerinde güvenle kullanabilirsin.": "You can safely use your balance for order payments.", "Bakiye hareketleri": "Balance Activity",
  "Yükleniyor…": "Loading…", "Henüz bakiye hareketin yok": "You don't have any balance activity yet",
  "Kasada telefon numaranı söyleyerek nakit bakiye yükleyebilirsin.": "You can add cash balance at the register by providing your phone number.",
  "Bildirimler": "Notifications", "Güncelsin": "You're all caught up", "Şu an için yeni bir duyuru yok.": "There are no new announcements right now.",
  "Sıralama menüsünü kapat": "Close sorting menu",
};

export const ARAYUZ_DESEN_CEVIRILERI = [
  [/^Masa (.+)'desin$/, "You're at Table $1"], [/^Masa (.+)$/, "Table $1"], [/^(\d+) ürün$/, "$1 products"],
  [/^(\d+) okunmamış$/, "$1 unread"], [/^(\d+) Puan ile kazanıldı$/, "Earned with $1 Points"], [/^(.+) daha$/, "$1 more"],
];
