export const SOZLUK = {
  tr: {
    common: { back:"Geri", close:"Kapat", home:"Ana Sayfa", menu:"Menüye Dön", decrease:"Azalt", increase:"Artır", remove:"Kaldır", included:"Dahil", excluded:"Haric: {{items}}", table:"Masa {{number}}", loading:"Hazırlanıyor…" },
    language: { label:"Dil seçimi" },
    welcome: { invalidQr:"Geçersiz QR", invalidQrHelp:"Masadaki QR kodu tekrar okutmayı dene.", goHome:"Ana Sayfaya Git", tableLabel:"MASA {{number}}", title:"Hoş Geldin! 👋", intro:"Nasıl devam etmek istersin? Üyeysen giriş yapıp puan kazanmaya devam edebilirsin. İlk kez geldiysen misafir olarak hemen sipariş verebilirsin.", signIn:"Giriş Yap", memberHint:"Üyeyim, puan kazanayım", guest:"Misafir Olarak Devam Et", guestHint:"Üye olmadan sipariş ver", serviceNote:"Siparişin Masa {{number}}'ye servis edilecek" },
    nav: { home:"Ana Sayfa", campaigns:"Kampanyalar", orders:"Sipariş", points:"Puanlarım", profile:"Profil", soon:"Yakında" },
    header: { hello:"Merhaba,", guest:"Misafir", friend:"Dostum", callStaff:"Personel çağır", notifications:"Bildirimler", cart:"Sepet", profile:"Profil", unread:"{{count}} okunmamış", upToDate:"Güncelsin", noNews:"Şu an için yeni bir duyuru yok.", tableLabel:"MASA {{number}}", callTitle:"Personel çağır", callIntro:"İhtiyacınızı seçin; salon personeli anında bilgilendirilsin.", callSeen:"Personel çağrınızı gördü ve masanıza geliyor.", callWaiting:"Çağrınız salondaki personele iletildi.", callDone:"Son çağrınız tamamlandı.", callAbsent:"Masada müşteri bulunamadığı için çağrı kapatıldı.", callOrder:"Sipariş vermek istiyorum", callOrderHint:"Menü ve sipariş desteği", callBill:"Hesap istiyorum", callBillHint:"Ödeme için personel gelsin", callNeed:"Bir ihtiyacım var", callNeedHint:"Peçete, çatal veya başka bir istek", callClean:"Masa temizliği", callCleanHint:"Masanın temizlenmesini istiyorum" },
    home: { completed:"TAMAMLANDI", stamp:"Damga", gift:"Hediye", membersOnly:"Üyelere özel", stampHint:"Giriş yap veya üye ol; {{category}} kategorisindeki alışverişlerinle damga biriktir.", nextReward:"SIRADAKİ ÖDÜL", remaining:"{{count}} {{unit}} daha", soldOut:"Tükendi", search:"Menüde ara", sort:"Sıralama seçenekleri", closeSort:"Sıralama menüsünü kapat", recommended:"Önerilen", priceAsc:"Fiyat: Artan", priceDesc:"Fiyat: Azalan", products:"Ürünler", allCategory:"Tüm {{category}}", count:"{{count}} ürün", noResult:"“{{query}}” için sonuç bulunamadı.", waitingProducts:"Menü ürünleri yönetim panelinden eklenmeyi bekliyor.", quantity:"Miktar", standard:"Standart", outOfStockAria:"{{name}} stokta yok", addAria:"{{name}} sepete ekle" },
    cart: { title:"Sepetim", empty:"Sepetin boş.", backToMenu:"Menüye Dön", gift:"HEDİYE 🎁", total:"Toplam", atTable:"Masa {{number}}'desin", checkout:"Ödemeye Geç", orderType:"Nasıl sipariş vermek istersin?", pickup:"Gel Al", tableService:"Masaya Servis" },
    campaigns: { title:"Özel Fırsatlar ve Kampanyalar", intro:"Sana özel hazırladığımız lezzetli fırsatları kaçırma.", active:"AKTİF", upcoming:"BAŞLAMADI", ended:"SONA ERDİ", membersOnly:"🔒 Üyelere Özel", inviteCode:"Davet kodun", loading:"Yükleniyor…", copied:"Kopyalandı", copy:"Kopyala", invites:"davet", pointsEarned:"puan kazanç", modalTitle:"Üyelere Özel Kampanya", modalText:"Bu kampanyadan faydalanmak için üye olmalısın.", register:"Üye Ol" },
    orders: { title:"Siparişlerim", empty:"Henüz siparişin yok", emptyHint:"Sipariş verdiğinde burada görünecek.", goMenu:"Menüye Git", loading:"Siparişler yükleniyor…", active:"Aktif Siparişler", history:"Geçmiş Siparişler", table:"Masa {{number}}", pickup:"Gel Al", total:"Toplam", points:"+{{points}} puan", paid:"✓ Ödeme tamamlandı", reorder:"🔁 Tekrar Sipariş Ver", reviewed:"Değerlendirmen alındı", review:"☆ Siparişi Değerlendir", ready:"Hazır ✓", preparing:"Hazırlanıyor", received:"Alındı", excluded:"Hariç: {{items}}", unavailable:"Bu siparişteki ürünler artık mevcut değil.", missing:"{{count}} ürün artık mevcut değil, eklenemedi." },
    rewards: { joinTitle:"Puan Kazanmaya Başla", joinText:"Puanlar üyelere özel. Üye ol, her siparişte puan biriktir, ödüller kazan.", total:"Toplam Puanım", point:"Puan", start:"Başlangıç", target:"Hediye {{unit}} ({{points}} Puan)", remaining:"Hediyeye sadece {{points}} puan kaldı!", market:"Ödül Marketi", buy:"{{name}} al", added:"{{name}} hediyelerine eklendi!", failed:"Ödül alınamadı.", history:"Puan Geçmişi", seeAll:"Tümünü Gör" },
    profile: { joinTitle:"Hesabını Oluştur", joinText:"Profil üyelere özel. Üye ol, siparişlerini ve puanlarını tek yerden yönet.", guest:"Misafir", notSignedIn:"Giriş yapmadınız", edit:"Düzenle", inviteCode:"Davet kodun", copied:"Kopyalandı", copy:"Kopyala", inviteText:"Kodunla kayıt olan arkadaşlarının her alışverişinden %5 puan kazanırsın.", invited:"Davet edilen", rewardedOrders:"Ödüllü sipariş", earnedPoints:"Kazanılan puan", wallet:"Cüzdanım", personal:"Kişisel Bilgiler", gifts:"Hediyelerim", orderHistory:"Sipariş Geçmişi", feedback:"Şikayet ve Geri Bildirim", support:"Yardım & Destek", twoFactor:"İki Adımlı Doğrulama", enabled:"Aktif", disabled:"Kapalı", logout:"Çıkış Yap", supportBrand:"BURGER PLUS DESTEK", supportTitle:"Nasıl yardımcı olabiliriz?", supportText:"Siparişin, kampanyalar veya hesabınla ilgili desteğe ihtiyaç duyarsan ekibimize ulaşabilirsin. Sipariş numaranı ve masa bilgini paylaşman çözümü hızlandırır.", supportHours:"Destek saatleri: Her gün 10:00 – 23:00" },
    qr: { title:"QR Okut", tableHelp:"Masandaki QR kodu çerçeveye getir, siparişini o masaya iletelim.", counterHelp:"Kasadaki QR kodu çerçeveye getirerek siparişini başlat.", opening:"Kamera açılıyor…", align:"QR kodu çerçeve içine hizala", invalid:"Bu QR güvenli bir masa erişim anahtarı içermiyor. Masadaki güncel QR kodunu okut.", permission:"Kamera izni verilmedi. Tarayıcı ayarlarından bu sayfa için kameraya izin verip yeniden dene.", unavailable:"Kameraya erişilemedi. Güvenli masa erişimi için masadaki QR kodunun okutulması gerekir.", continue:"Devam Et" },
    product: { menuContent:"Menü İçeriği", burger:"Burger", side:"Yan lezzet", drink:"İçecek", nutrition:"Besin Değerleri", calories:"Kalori", protein:"Protein", carbs:"Karbonhidrat", fat:"Yağ", allergen:"Alerjen Bilgisi", ingredients:"İçindekiler", removeHint:"İstemediğin malzemeye dokun", pairsWell:"YANINDA İYİ GİDER", completeOrder:"Siparişini tamamla", add:"Ekle", addToCart:"Sepete Ekle", addToCartPrice:"Sepete Ekle — {{price}}", outOfStock:"Stokta yok", requiredChoice:"Ekstra malzeme seç", quantity:"Ürün miktarı", standard:"Standart: {{amount}}", incrementPrice:"Her +{{amount}} için +{{price}}", quantityChoice:"{{name}} seçimi", decreaseQuantity:"Gramajı azalt", increaseQuantity:"Gramajı artır", sizeChoice:"Boyut seçimi", sizeOf:"{{name}} boyutu", extraChoose:"Ekstra malzeme seç", choiceRange:"{{min}}en fazla {{max}} seçim", free:"Ücretsiz", minimumChoice:"Devam etmek için en az {{count}} seçim yapmalısın." },
    payment: { title:"Ödeme", empty:"Sepetin boş, önce ürün ekle.", guest:"👤 Misafir olarak devam ediyorsun", summary:"Sipariş özeti", type:"Ödeme türü", online:"Online ödeme", onlineHint:"Şimdi güvenle öde", wallet:"Cüzdan bakiyesi", loginRequired:"Üye girişi gerekli", unavailable:"Şu anda kullanılamıyor", available:"{{amount}} TL kullanılabilir", cash:"Nakit ödeme", tableOnly:"Yalnızca masada", checkingTable:"Masa kontrol ediliyor", payAfterMeal:"Yemek sonunda öde", staffMustOpen:"Personelin masayı açması gerekli", cashWarning:"Nakit sipariş için personelden Masa {{number}}'yi açmasını iste.", tableService:"Masa {{number}} — Masaya Servis", contact:"İletişim bilgileri", contactHint:"Kart bilgilerin İyzico’nun güvenli ödeme sayfasında girilir. Normal siparişte T.C. kimlik ve adres bilgisi istenmez.", firstName:"Ad", lastName:"Soyad", email:"E-posta", phone:"Telefon", how:"Nasıl ödemek istersin?", full:"Tamamını Öde", fullHint:"Hesabın tamamını sen öde", equal:"Eşit Böl", equalHint:"Çoklu ödeme oturumu ile yakında", byProduct:"Ürüne Göre", byProductHint:"Sadece kendi ürünlerini öde", insufficient:"Cüzdan bakiyen bu sipariş için yetersiz. Kasadan nakit yükleme yapabilirsin.", people:"Kaç kişi paylaşıyor?", perPerson:"Kişi başı {{amount}}", chooseProducts:"Ödeyeceğin ürünleri seç", pointsCash:"Nakit tahsil edildiğinde", pointsPayment:"Bu ödemeden", pointsEarn:"{{points}} puan kazanacaksın", payable:"Ödenecek Tutar", sendOrder:"Personel Onayına Gönder", pay:"Ödeme Yap", sending:"Sipariş gönderiliyor…", preparing:"Güvenli ödeme hazırlanıyor…", orderNo:"Sipariş no", tablePayable:"Masada ödenecek", rejected:"Sipariş Onaylanmadı", sent:"Sipariş Mutfağa İletildi", waiting:"Personel Onayı Bekleniyor", rejectedInfo:"Sipariş personel tarafından reddedildi. Detay için personelden yardım isteyebilirsin.", sentInfo:"Siparişin hazırlanıyor. Nakit ödemeyi yemeğin sonunda personele yapabilirsin.", waitingInfo:"Personel siparişini kontrol ediyor. Onaylanmadan mutfağa iletilmeyecek." },
    success: { verifying:"Ödeme sonucun doğrulanıyor…", backToPayment:"Ödemeye Dön", noPayment:"Görüntülenecek ödeme yok.", title:"Ödeme Başarılı!", preparing:"Siparişin Hazırlanıyor", kitchen:"Mutfağa iletildi, hazırlanıyor.", paid:"Ödenen Tutar", points:"Kazandığın Puan", full:"Tamamı ödendi", equal:"Eşit bölüşüldü", byProduct:"Ürüne göre ödendi", guestNote:"Afiyet olsun! Üye olsaydın bu ödemeden puan kazanırdın. 🎁", totalPoints:"Toplam puanın: {{points}}", backHome:"Ana Sayfaya Dön", seePoints:"Puanlarımı Gör", celebration:"Siparişin Alındı 🎉" }
  },
  en: {
    common: { back:"Back", close:"Close", home:"Home", menu:"Back to Menu", decrease:"Decrease", increase:"Increase", remove:"Remove", included:"Included", excluded:"No: {{items}}", table:"Table {{number}}", loading:"Preparing…" },
    language: { label:"Language selection" },
    welcome: { invalidQr:"Invalid QR Code", invalidQrHelp:"Please scan the QR code on your table again.", goHome:"Go to Home", tableLabel:"TABLE {{number}}", title:"Welcome! 👋", intro:"How would you like to continue? Sign in to keep earning points, or order immediately as a guest if this is your first visit.", signIn:"Sign In", memberHint:"I'm a member, earn points", guest:"Continue as Guest", guestHint:"Order without an account", serviceNote:"Your order will be served to Table {{number}}" },
    nav: { home:"Home", campaigns:"Offers", orders:"Orders", points:"My Points", profile:"Profile", soon:"Coming soon" },
    header: { hello:"Hello,", guest:"Guest", friend:"Friend", callStaff:"Call staff", notifications:"Notifications", cart:"Cart", profile:"Profile", unread:"{{count}} unread", upToDate:"You're up to date", noNews:"There are no new announcements.", tableLabel:"TABLE {{number}}", callTitle:"Call staff", callIntro:"Choose what you need and the floor team will be notified immediately.", callSeen:"A staff member saw your request and is coming to your table.", callWaiting:"Your request was sent to the floor team.", callDone:"Your last request was completed.", callAbsent:"The request was closed because no guest was found at the table.", callOrder:"I want to order", callOrderHint:"Menu and ordering assistance", callBill:"I'd like the bill", callBillHint:"Ask staff to help with payment", callNeed:"I need something", callNeedHint:"Napkins, cutlery or another request", callClean:"Clean the table", callCleanHint:"I'd like the table to be cleaned" },
    home: { completed:"COMPLETED", stamp:"Stamp", gift:"Gift", membersOnly:"Members only", stampHint:"Sign in or register to collect stamps with purchases from {{category}}.", nextReward:"NEXT REWARD", remaining:"{{count}} {{unit}} remaining", soldOut:"Sold out", search:"Search the menu", sort:"Sorting options", closeSort:"Close sorting menu", recommended:"Recommended", priceAsc:"Price: Low to High", priceDesc:"Price: High to Low", products:"Products", allCategory:"All {{category}}", count:"{{count}} products", noResult:"No results found for “{{query}}”.", waitingProducts:"Menu products are waiting to be added from the management panel.", quantity:"Quantity", standard:"Standard", outOfStockAria:"{{name}} is out of stock", addAria:"Add {{name}} to cart" },
    cart: { title:"My Cart", empty:"Your cart is empty.", backToMenu:"Back to Menu", gift:"GIFT 🎁", total:"Total", atTable:"You're at Table {{number}}", checkout:"Proceed to Payment", orderType:"How would you like to order?", pickup:"Pickup", tableService:"Table Service" },
    campaigns: { title:"Special Offers and Campaigns", intro:"Don't miss the delicious offers prepared for you.", active:"ACTIVE", upcoming:"UPCOMING", ended:"ENDED", membersOnly:"🔒 Members Only", inviteCode:"Your invite code", loading:"Loading…", copied:"Copied", copy:"Copy", invites:"invites", pointsEarned:"points earned", modalTitle:"Members-Only Campaign", modalText:"You need to become a member to use this campaign.", register:"Register" },
    orders: { title:"My Orders", empty:"You don't have any orders yet", emptyHint:"Your orders will appear here.", goMenu:"Go to Menu", loading:"Loading orders…", active:"Active Orders", history:"Order History", table:"Table {{number}}", pickup:"Pickup", total:"Total", points:"+{{points}} points", paid:"✓ Payment completed", reorder:"🔁 Order Again", reviewed:"Review received", review:"☆ Review Order", ready:"Ready ✓", preparing:"Preparing", received:"Received", excluded:"No: {{items}}", unavailable:"The products in this order are no longer available.", missing:"{{count}} product(s) are no longer available and were not added." },
    rewards: { joinTitle:"Start Earning Points", joinText:"Points are for members. Join to collect points with every order and redeem rewards.", total:"My Total Points", point:"Points", start:"Start", target:"Free {{unit}} ({{points}} Points)", remaining:"Only {{points}} points left until your reward!", market:"Rewards", buy:"Redeem {{name}}", added:"{{name}} was added to your rewards!", failed:"The reward could not be redeemed.", history:"Points History", seeAll:"See All" },
    profile: { joinTitle:"Create Your Account", joinText:"Profiles are for members. Join to manage your orders and points in one place.", guest:"Guest", notSignedIn:"You are not signed in", edit:"Edit", inviteCode:"Your invite code", copied:"Copied", copy:"Copy", inviteText:"Earn 5% in points from every purchase made by friends who join with your code.", invited:"Invited", rewardedOrders:"Rewarded orders", earnedPoints:"Points earned", wallet:"My Wallet", personal:"Personal Information", gifts:"My Rewards", orderHistory:"Order History", feedback:"Complaints & Feedback", support:"Help & Support", twoFactor:"Two-Step Verification", enabled:"On", disabled:"Off", logout:"Sign Out", supportBrand:"BURGER PLUS SUPPORT", supportTitle:"How can we help?", supportText:"Contact us if you need help with an order, offer, or your account. Sharing your order number and table helps us resolve it faster.", supportHours:"Support hours: Daily, 10:00–23:00" },
    qr: { title:"Scan QR", tableHelp:"Place the QR code on your table inside the frame to send the order to that table.", counterHelp:"Place the QR code at the counter inside the frame to start your order.", opening:"Opening camera…", align:"Align the QR code inside the frame", invalid:"This QR code does not contain a secure table access key. Scan the current QR code on the table.", permission:"Camera permission was denied. Allow camera access for this page in your browser settings and try again.", unavailable:"The camera could not be accessed. Please scan the QR code on the table for secure access.", continue:"Continue" },
    product: { menuContent:"Menu Contents", burger:"Burger", side:"Side", drink:"Drink", nutrition:"Nutrition", calories:"Calories", protein:"Protein", carbs:"Carbohydrates", fat:"Fat", allergen:"Allergen Information", ingredients:"Ingredients", removeHint:"Tap an ingredient you don't want", pairsWell:"GOES WELL WITH", completeOrder:"Complete your order", add:"Add", addToCart:"Add to Cart", addToCartPrice:"Add to Cart — {{price}}", outOfStock:"Out of stock", requiredChoice:"Choose an extra", quantity:"Product quantity", standard:"Standard: {{amount}}", incrementPrice:"Each +{{amount}} costs +{{price}}", quantityChoice:"Choose {{name}}", decreaseQuantity:"Decrease quantity", increaseQuantity:"Increase quantity", sizeChoice:"Choose size", sizeOf:"{{name}} size", extraChoose:"Choose extras", choiceRange:"{{min}}up to {{max}} choices", free:"Free", minimumChoice:"Choose at least {{count}} option(s) to continue." },
    payment: { title:"Payment", empty:"Your cart is empty. Add a product first.", guest:"👤 You're continuing as a guest", summary:"Order summary", type:"Payment method", online:"Online payment", onlineHint:"Pay securely now", wallet:"Wallet balance", loginRequired:"Member sign-in required", unavailable:"Currently unavailable", available:"{{amount}} TRY available", cash:"Cash payment", tableOnly:"At the table only", checkingTable:"Checking table", payAfterMeal:"Pay after your meal", staffMustOpen:"Staff must open the table", cashWarning:"Ask a staff member to open Table {{number}} for a cash order.", tableService:"Table {{number}} — Table Service", contact:"Contact information", contactHint:"Card details are entered on Iyzico's secure payment page. Standard orders do not require ID or address information.", firstName:"First name", lastName:"Last name", email:"Email", phone:"Phone", how:"How would you like to pay?", full:"Pay in Full", fullHint:"Pay the entire bill", equal:"Split Equally", equalHint:"Multi-payment sessions are coming soon", byProduct:"By Product", byProductHint:"Pay only for your own products", insufficient:"Your wallet balance is insufficient. You can add cash at the register.", people:"How many people are sharing?", perPerson:"{{amount}} per person", chooseProducts:"Select the products you'll pay for", pointsCash:"When cash is collected", pointsPayment:"From this payment", pointsEarn:"you'll earn {{points}} points", payable:"Amount Due", sendOrder:"Send for Staff Approval", pay:"Pay Now", sending:"Sending order…", preparing:"Preparing secure payment…", orderNo:"Order no.", tablePayable:"Payable at table", rejected:"Order Not Approved", sent:"Order Sent to Kitchen", waiting:"Waiting for Staff Approval", rejectedInfo:"Staff rejected the order. Ask a staff member for details.", sentInfo:"Your order is being prepared. Pay cash to staff after your meal.", waitingInfo:"Staff are reviewing your order. It will not be sent to the kitchen before approval." },
    success: { verifying:"Verifying your payment…", backToPayment:"Back to Payment", noPayment:"No payment to display.", title:"Payment Successful!", preparing:"Your Order Is Being Prepared", kitchen:"Sent to the kitchen and being prepared.", paid:"Amount Paid", points:"Points Earned", full:"Paid in full", equal:"Split equally", byProduct:"Paid by product", guestNote:"Enjoy your meal! You could have earned points from this payment as a member. 🎁", totalPoints:"Total points: {{points}}", backHome:"Back to Home", seePoints:"View My Points", celebration:"Order Received 🎉" }
  }
};

export const DESTEKLENEN_DILLER = ["tr", "en"];
